<?php include __DIR__ . '/../header.html' ?>
    <div class="container">
        <div class="row">
            <h3>Listagem de categorias</h3>
            <a href="/categories/create">Nova categoria</a>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($categories as $category): ?>
                    <tr>
                        <td><?php echo $category->getId(); ?></td>
                        <td><?php echo $category->getName(); ?></td>
                        <td><?php echo "<a href='/categories/{$category->getId()}/edit'>Editar</a>"; ?> |
                            <?php echo "<a href='/categories/{$category->getId()}/remove'>Excluir</a>"; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html' ?>